version: '3.9'
services:
    overseerr:
      container_name: overseerr_container
      image: lscr.io/linuxserver/overseerr:latest
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
      volumes:
        - /overseerr/config:/config
      ports:
        - 5055:5055
      restart: unless-stopped

    prowlarr:
      image: lscr.io/linuxserver/prowlarr:develop
      container_name: prowlarr_container
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
      volumes:
        - /prowlarr/config:/config
      ports:
        - 9696:9696
      restart: unless-stopped
    
    radarr:
      image: lscr.io/linuxserver/radarr:latest
      container_name: radarr_container
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
      volumes:
        - /radarr/config:/config
        - /radarr/movies:/movies 
        - /radarr/downloads:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped
      depends_on:
        -  overseerr
        -  prowlarr

    sonarr:
      image: lscr.io/linuxserver/sonarr:latest
      container_name: sonarr_container
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Paris
      volumes:
        - /sonarr/config:/config
        - /sonarr/tvseries:/tv
        - /sonarr/downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped
      depends_on:
        -  overseerr
        -  prowlarr

      bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr_container
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Paris
        volumes:
          - /bazarr/config:/config
          - /bazarr/movies:/movies 
          - /bazarr/tv:/tv 
        ports:
          - 6767:6767
        restart: unless-stopped
        depends_on:
        -  overseerr
        -  prowlarr
        -  radarr
        -  sonarr
      
      plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
          # - PLEX_CLAIM= 
        volumes:
          - /plex/config:/config
          - /plex/tvseries:/tv
          - /plex/movies:/movies
        restart: unless-stopped
        depends_on:
          -  overseerr
          -  prowlarr
          -  radarr
          -  sonarr
          -  bazarr

